enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#[YouTube]
#build-mode = "module"
#excluded-patches = "'GmsCore support'"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
#uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

#[Reddit-Morphe]
#app-name = "Reddit"
#rv-brand = "Morphe"
#build-mode = "both"
#patches-source = "MorpheApp/morphe-patches"
#cli-source = "MorpheApp/morphe-cli"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
#uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
#dpi = "120-640dpi"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"
